### ISSUE TITLE
キーの表示が重なっている

### ISSUE THREAD

**Issue by arigayas** [Ponta2929/KeyTouchView#1]
### 使用バージョン：1.0.0

![image](https://user-images.githubusercontent.com/11251874/100659198-a0728180-3393-11eb-8b1b-f91db89f395e.png)
### 設定：
![image](https://user-images.githubusercontent.com/11251874/100659456-0232eb80-3394-11eb-84fe-91e0ab6840dc.png)
![image](https://user-images.githubusercontent.com/11251874/100659550-2262aa80-3394-11eb-8333-a2a7b1254f62.png)
![image](https://user-images.githubusercontent.com/11251874/100659628-39a19800-3394-11eb-8244-345ded854e91.png)

**Comment by Ponta2929** [comment]
仕様です。設定画面を開いた状態で動かしてください。
